create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(120) not null unique,
    master_password_hash varchar(255) not null,
    encryption_salt bytea not null
);

create table vault_entries (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id),
    site varchar(255) not null,
    login_username varchar(255) not null,
    category varchar(255),
    password_iv varchar(255) not null,
    encrypted_password text not null,
    notes_iv varchar(255) not null,
    encrypted_notes text not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_vault_entries_owner on vault_entries(owner_id);